### PR TITLE
Fix maps, kill proxy implementation for Maps

### LINKED ISSUE #472: Unexpected access to original frozen objects while updating a map
## 🐛 Bug Report

When updating several objects in a `Map`, writing to an object that should be mutable throws an error in some cases.

## To Reproduce

This code reproduces the error.
```
import {produce} from "immer"

const project = produce(new Map(), draft => {
  draft.set("bar1", {blocked: false})
  draft.set("bar2", {blocked: false})
})

// Read before write -- no error
produce(project, draft => {
  const bar1 = draft.get("bar1")
  const bar2 = draft.get("bar2")
  bar1.blocked = true
  bar2.blocked = true
})

// Read/write interleaved -- error
produce(project, draft => {
  const bar1 = draft.get("bar1")
  bar1.blocked = true
  const bar2 = draft.get("bar2")
  bar2.blocked = true // TypeError: "blocked" is read-only
}) 
```

## Expected behavior

Writing to objects inside a map in `produce` should not error. More broadly it seems like accessing frozen objects in `produce` should only be possible with `original`.

## Link to repro (highly encouraged)

[CodeSandbox demo](https://codesandbox.io/s/immer-sandbox-84tkm)

## Environment

- **Immer version: 5.0.0**
- [x] Occurs with `setUseProxies(true)`
- [ ] Occurs with `setUseProxies(false)` (ES5 only)

### PR DESCRIPTION
**Pull request by mweststrate**
- [x] finish clean code branch first
- [x] test / mention map keys are not drafted (or open issue to do so)
- [x] test / mention external data objects are not draft (or open issue to do so)

Should fix #472, #466, #449

### CODE REVIEW

File: __tests__/map-set.js [hunk 1]
```diff
@@ -0,0 +1,176 @@
...
+runBaseTest("proxy (no freeze)", true, false)
+runBaseTest("proxy (autofreeze)", true, true)
+runBaseTest("proxy (autofreeze)(patch listener)", true, true, true)
+runBaseTest("es5 (no freeze)", false, false)
+runBaseTest("es5 (autofreeze)", false, true)
+runBaseTest("es5 (autofreeze)(patch listener)", false, true, true)
+
+function runBaseTest(name, useProxies, autoFreeze, useListener) {
+	const listener = useListener ? function() {} : undefined
+	const {produce, produceWithPatches} = createPatchedImmer({
```
Comment (oriSomething) [inline __tests__/map-set.js]: I think to prevent bugs in future, it would be better be inside `beforeEach`. Otherwise, If `new Immer()` isn't 100% clean from global environment it will causes bugs in testing, as was before

**Comment by JackCA** [comment]
Any change we see this go out soon?

**Comment by mweststrate** [comment]
I expect and of next week or early after that. Got most functionality
working again, but the devil is in the details here

**Comment by runnez** [comment]
@mweststrate I could help with something if needed

File: tsconfig.json [hunk 2]
```diff
@@ -2,6 +2,8 @@
   "include": ["src"],
   "compilerOptions": {
     "lib": ["es2015"],
+    // TODO: change to ES5 and make sure maps still work
```
Comment (runnez) [inline tsconfig.json]: I tried to test current implementation with extending map (I like it and I'm curious how it works :) 
I found some issue with TS output to ES5 and V8 
```
Uncaught TypeError: Constructor Map requires 'new'
    at DraftMap.Map (<anonymous>)
    at new DraftMap (<anonymous>:19:28)
    at <anonymous>:1:1
```
https://github.com/microsoft/TypeScript/issues/10853

Comment (mweststrate) [reply tsconfig.json]: Yeah, that is how far I got :D. Probably, if extending is not possible, we should do a dirty set prototype hack. The most important thing is that `draftMap instanceof Map` passes, beyond that we don't really make / need any super calls

Comment (mweststrate) [reply tsconfig.json]: This is probably an interesting thing to figure out if you are interested :) Beyond that it might be a bit hard to help, as I am a bit all over the place, refactoring to reduce code duplication, (or just untangle some spaghetti that grew over time), so it is kinda hard to split that up
